// frontend/src/app/components/results-table/results-table.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TimeEntry } from '../../services/toggl.service';

@Component({
  selector: 'app-results-table',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './results-table.component.html',
  styleUrl: './results-table.component.css'
})
export class ResultsTableComponent {
  @Input() timeEntries: TimeEntry[] = [];

  formatDuration(seconds: number): string {
    const hours = Math.floor(seconds / 3600);
    const minutes = Math.floor((seconds % 3600) / 60);
    return `${hours}h ${minutes}m`;
  }

  formatDate(dateString: string): string {
    const date = new Date(dateString);
    return date.toLocaleDateString('es-ES', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  }

  getTotalDuration(): number {
    return this.timeEntries.reduce((total, entry) => total + entry.duration, 0);
  }

  getTotalBillableDuration(): number {
    return this.timeEntries
      .filter(entry => entry.billable)
      .reduce((total, entry) => total + entry.duration, 0);
  }
}

<div class="results-table-container">
  <h2>Resultados</h2>

  <div class="summary">
    <div class="summary-item">
      <span class="summary-label">Total de entradas:</span>
      <span class="summary-value">{{ timeEntries.length }}</span>
    </div>
    <div class="summary-item">
      <span class="summary-label">Tiempo total:</span>
      <span class="summary-value">{{ formatDuration(getTotalDuration()) }}</span>
    </div>
    <div class="summary-item">
      <span class="summary-label">Tiempo facturable:</span>
      <span class="summary-value">{{ formatDuration(getTotalBillableDuration()) }}</span>
    </div>
  </div>

  <div class="table-wrapper">
    <table class="results-table">
      <thead>
        <tr>
          <th>Cuenta</th>
          <th>Descripción</th>
          <th>Cliente</th>
          <th>Proyecto</th>
          <th>Inicio</th>
          <th>Fin</th>
          <th>Duración</th>
          <th>Tags</th>
          <th>Responsable</th>
          <th>Facturable</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let entry of timeEntries">
          <td>{{ entry.account_name }}</td>
          <td>{{ entry.description || 'Sin descripción' }}</td>
          <td>{{ entry.client_name || '-' }}</td>
          <td>{{ entry.project_name || '-' }}</td>
          <td>{{ formatDate(entry.start) }}</td>
          <td>{{ entry.stop ? formatDate(entry.stop) : 'En curso' }}</td>
          <td>{{ formatDuration(entry.duration) }}</td>
          <td>
            <span *ngIf="entry.tags && entry.tags.length > 0" class="tags">
              <span *ngFor="let tag of entry.tags" class="tag">{{ tag }}</span>
            </span>
            <span *ngIf="!entry.tags || entry.tags.length === 0">-</span>
          </td>
          <td>{{ entry.user_name || entry.user_id || '-' }}</td>
          <td>
            <span [class.billable]="entry.billable" [class.not-billable]="!entry.billable">
              {{ entry.billable ? 'Sí' : 'No' }}
            </span>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <div *ngIf="timeEntries.length === 0" class="empty-results">
    <p>No se encontraron entradas de tiempo con los filtros seleccionados.</p>
  </div>
</div>

// src/components/ResultsTable.tsx
import type { TimeEntryResult } from '../types';
import './ResultsTable.css';

interface ResultsTableProps {
  results: TimeEntryResult[];
  loading: boolean;
}

export const ResultsTable = ({ results, loading }: ResultsTableProps) => {
  const formatDuration = (seconds: number): string => {
    const hours = Math.floor(seconds / 3600);
    const minutes = Math.floor((seconds % 3600) / 60);
    return `${hours}h ${minutes}m`;
  };

  const formatDate = (dateString: string): string => {
    const date = new Date(dateString);
    return date.toLocaleDateString('es-ES', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  const totalDuration = results.reduce((sum, entry) => sum + entry.duration, 0);

  if (loading) {
    return (
      <div className="results-table-container">
        <div className="loading">Cargando resultados...</div>
      </div>
    );
  }

  if (results.length === 0) {
    return (
      <div className="results-table-container">
        <div className="empty-message">No hay resultados para mostrar. Añade filtros y carga los datos.</div>
      </div>
    );
  }

  return (
    <div className="results-table-container">
      <div className="results-summary">
        <h3>Resumen</h3>
        <p>
          <strong>Total de entradas:</strong> {results.length}
        </p>
        <p>
          <strong>Tiempo total:</strong> {formatDuration(totalDuration)}
        </p>
      </div>

      <div className="table-wrapper">
        <table className="results-table">
          <thead>
            <tr>
              <th>Cuenta</th>
              <th>Responsable</th>
              <th>Descripción</th>
              <th>Cliente</th>
              <th>Proyecto</th>
              <th>Tag</th>
              <th>Inicio</th>
              <th>Fin</th>
              <th>Duración</th>
              <th>Facturable</th>
            </tr>
          </thead>
          <tbody>
            {results.map((entry) => (
              <tr key={entry.id}>
                <td>{entry.accountName}</td>
                <td>{entry.responsible}</td>
                <td>{entry.description || '-'}</td>
                <td>{entry.client || '-'}</td>
                <td>{entry.project || '-'}</td>
                <td>
                  {entry.tags && entry.tags.length > 0
                    ? entry.tags.join(', ')
                    : entry.tag || '-'}
                </td>
                <td>{formatDate(entry.start)}</td>
                <td>{entry.stop ? formatDate(entry.stop) : 'En curso'}</td>
                <td>{formatDuration(entry.duration)}</td>
                <td>{entry.billable ? 'Sí' : 'No'}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};
